# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-25 03:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('NM', 'Normal'), ('GS', 'Guessing'), ('JD', 'Judge'), ('LD', 'Lucky Draw')], default='NM', max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('base_score', models.IntegerField(default=0)),
                ('is_active', models.BooleanField()),
                ('display_leaderboard', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GamePrize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=1)),
                ('score', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Game')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_value', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Game')),
                ('game_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartialScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveSmallIntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('game_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-percentage'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AggregatedScore',
            fields=[
                ('score_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scoreboard.Score')),
            ],
            bases=('scoreboard.score',),
        ),
        migrations.CreateModel(
            name='PointCode',
            fields=[
                ('score_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scoreboard.Score')),
                ('code', models.CharField(max_length=255)),
                ('consumed_on', models.DateField(blank=True, null=True)),
            ],
            bases=('scoreboard.score',),
        ),
        migrations.CreateModel(
            name='SingleScore',
            fields=[
                ('score_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scoreboard.Score')),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position'],
            },
            bases=('scoreboard.score',),
        ),
        migrations.AddField(
            model_name='score',
            name='game_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scoreboard.GameSession'),
        ),
        migrations.AddField(
            model_name='score',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
        migrations.AddField(
            model_name='partialscore',
            name='aggregated_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.AggregatedScore'),
        ),
        migrations.AlterUniqueTogether(
            name='gameprize',
            unique_together=set([('game', 'rank')]),
        ),
        migrations.AlterUniqueTogether(
            name='partialscore',
            unique_together=set([('aggregated_score', 'game_master')]),
        ),
    ]
