# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-01 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='changeable_score',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
