# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-14 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameprize',
            options={'ordering': ['rank']},
        ),
    ]
