# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-23 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('NM', 'Normal'), ('GS', 'Guessing'), ('JD', 'Judge'), ('LD', 'Lucky Draw')], default='NM', max_length=2),
        ),
    ]
