# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-23 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='base_score',
            field=models.IntegerField(default=0),
        ),
    ]
