# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_auto_20160428_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='game',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Game'),
            preserve_default=False,
        ),
    ]
