# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-01 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_game_changeable_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='changeable_score',
            field=models.BooleanField(default=False),
        ),
    ]
