# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-14 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_auto_20160614_2315'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guess',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='guess',
            name='game_session',
        ),
        migrations.RemoveField(
            model_name='guess',
            name='player',
        ),
        migrations.DeleteModel(
            name='Guess',
        ),
    ]
