# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-17 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_auto_20160614_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='singlescore',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
