# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-15 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_auto_20160615_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='is_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
