# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-17 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_auto_20160617_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
