# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_auto_20160428_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePrize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=1)),
                ('score', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Game')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='gameprize',
            unique_together=set([('game', 'rank')]),
        ),
    ]
