# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-15 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0004_gamesession_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
