# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0006_auto_20160430_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
