# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0007_score_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('game_session', 'position')]),
        ),
    ]
