# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-05 06:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0002_remove_player_points'),
        ('scoreboard', '0008_auto_20160430_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregateGameSession',
            fields=[
                ('gamesession_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scoreboard.GameSession')),
                ('players', models.ManyToManyField(to='players.Player')),
            ],
            bases=('scoreboard.gamesession',),
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PartialScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('percentage', models.PositiveSmallIntegerField(default=0)),
                ('game_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.GameSession')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
            options={
                'ordering': ['-percentage'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('NM', 'Normal'), ('GS', 'Guessing'), ('JD', 'Judge')], default='NM', max_length=2),
        ),
        migrations.AddField(
            model_name='guess',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Game'),
        ),
        migrations.AddField(
            model_name='guess',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.GameSession'),
        ),
    ]
