# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-05 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0009_auto_20160605_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.GameSession'),
        ),
        migrations.AlterField(
            model_name='guess',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
    ]
