# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-05 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_player_points'),
        ('scoreboard', '0010_auto_20160605_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.GameSession')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='partialscore',
            name='game_session',
        ),
        migrations.RemoveField(
            model_name='partialscore',
            name='player',
        ),
        migrations.AddField(
            model_name='partialscore',
            name='aggregated_score',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scoreboard.AggregatedScore'),
            preserve_default=False,
        ),
    ]
