# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-05 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0012_auto_20160605_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guess',
            options={'verbose_name_plural': 'Guesses'},
        ),
        migrations.AddField(
            model_name='gamesession',
            name='guess_value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
