# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-05 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0013_auto_20160606_0030'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guess',
            unique_together=set([('game_session', 'player')]),
        ),
    ]
