# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-10 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0015_auto_20160610_2356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AggregateGameSession',
        ),
    ]
