# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-15 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guess',
            old_name='game_sesion',
            new_name='game_session',
        ),
    ]
