# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-25 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('scoreboard', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffleticket',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Game'),
        ),
        migrations.AddField(
            model_name='raffleticket',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
        migrations.AddField(
            model_name='guess',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.GameSession'),
        ),
        migrations.AddField(
            model_name='guess',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
        migrations.AddField(
            model_name='draw',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Game'),
        ),
        migrations.AddField(
            model_name='draw',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
    ]
