# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-22 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='guess',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
