# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-23 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20160623_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='winning_ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.RaffleTicket'),
        ),
    ]
