# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-23 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('games', '0003_auto_20160623_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draw',
            name='winning_ticket',
        ),
        migrations.AddField(
            model_name='draw',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
    ]
